baseURL = 'https://5e3a.github.io/'
languageCode = 'es'
title = '5E3A(DevBlog)'
theme = "PaperMod"

[params]
    env = "production"
    description = "Bitácora personal sobre arquitectura, desarrollo de software y conceptos técnicos. Built with Hugo & PaperMod."
    author = "Sebastian"
    
    # Configuración de apariencia
    defaultTheme = "auto" # Cambia entre luz/oscuridad según el sistema
    showCodeCopyButtons = true # Ideal para tus posts de Go/HTMX
    showReadingTime = true
    showShareButtons = false
    showPostNavLinks = true
    showBreadCrumbs = false
    showRssButtonInSectionTermList = false
    showToc = true
    showAllPagesInArchive = true
    showPageNums = false

[params.homeInfoParams]
    Title = "5E3A"
    Content = """
    <p><strong>Bienvenido a mi bitácora personal.</strong></p>
    <br/>
<p>
En este espacio comparto contenido sobre <b>desarrollo de software</b> 
y su entorno, un área que me motiva a la mejora continua 
y a la que me dedico profesionalmente hace varios años.
</p>
<br/>
<p>
Gran parte del contenido aquí publicado es asistido por <b>Inteligencia Artificial</b> 
para optimizar la frecuencia de creación. Si bien cada artículo pasa por mi filtro 
técnico y experiencia, este blog también es mi <b>laboratorio para explorar tecnologías 
nuevas y temas relacionados al desarrollo</b>. Como en todo entorno de experimentación, 
recomiendo siempre validar estos conceptos con la documentación oficial y/o profesionales 
del área específicas.
</p>
<br/>
<p>¡Gracias por pasar!</p>
<div style="text-align: right;" class="home-info"><h3>5E3Astian :)</h3>Software Developer</div>
"""

[params.shareButtons]
    twitter = false
    linkedin = false
    reddit = false
    facebook = false
    whatsapp = false
    telegram = false
    ycombinator = false

    # Menú de navegación
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 5

    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 10

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 15

    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "/archives/"
        weight = 20

[markup.highlight]
    noClasses = false
    style = "monokai" # Resaltado de código tipo VS Code